version: '3'

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile.hkabtrak
    container_name: hkabtrak
    expose:
      - "1473"
    environment:
      - FLASK_ENV=production

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask
    volumes:
      - ./certs:/etc/nginx/certs
      - ./nginx.conf:/etc/nginx/nginx.conf

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./nginx.conf:/etc/nginx/nginx.conf
